In [1]:
import numpy as np
import random

lx = 4
ly = lx

spin=np.zeros((lx,ly),dtype=float)

#initialise spins randomly

for i in range(lx):
    for j in range(ly):
        r=random.random()
        if(r<0.5): spin[i,j]=-1
        if(r>=0.5): spin[i,j]=1

print(spin)

def E_spin(spin, lx , ly):
    '''spin: numpy array
             spin matrix

       lx, ly: Interger
               Dimensions of the spin array 
    '''
    spin_x = spin
    # print(f"{spin = }")
   
    E = 0
    for i in range(lx):
        for j in range(ly):
            E += -spin_x[i, j]*(spin_x[np.mod(i-1,lx),j] + spin_x[np.mod(i+1, lx),j] + spin_x[i,np.mod(j-1,ly)] + spin_x[i,np.mod(j+1,ly)])
            spin_x[i, j] = 0
    # print(f"{spin = }")
    # why does the spin array become all zeros, spin_X sould be all zeros but the but spin should not
    return E

# I calculate the energy of a point and then once I calculated all the the interactions with nearest neighbours I set the spin to zero

[[-1. -1. -1. -1.]
 [ 1.  1.  1. -1.]
 [ 1. -1.  1. -1.]
 [ 1.  1.  1.  1.]]


In [11]:
super_spin = np.zeros((10,lx,ly), dtype = float)

super_spin[9, :, :] = spin
print(super_spin)

[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[-1. -1. -1. -1.]
  [ 1.  1.  1. -1.]
  [ 1. -1.  1. -1.]
  [ 1.  1.  1.  1.]]]


## Find the energy of the array above

In [2]:
# E = E_spin(spin, lx, ly)
# print(f"{E = }")

In [3]:
spin_new = spin
for i in range(lx):
    for j in range(ly):

#select spin randomly
        itrial=np.random.randint(0,lx)
        jtrial=np.random.randint(0,ly)
        # this should flip one spin in the matrix, i think
        print(f"{itrial = }\n{jtrial = }")
        spin_new[itrial,jtrial] = -spin[itrial,jtrial]
        print(spin_new)

itrial = 1
jtrial = 3
[[ 1. -1. -1. -1.]
 [ 1.  1. -1. -1.]
 [-1.  1.  1. -1.]
 [ 1.  1.  1. -1.]]
itrial = 1
jtrial = 2
[[ 1. -1. -1. -1.]
 [ 1.  1.  1. -1.]
 [-1.  1.  1. -1.]
 [ 1.  1.  1. -1.]]
itrial = 0
jtrial = 3
[[ 1. -1. -1.  1.]
 [ 1.  1.  1. -1.]
 [-1.  1.  1. -1.]
 [ 1.  1.  1. -1.]]
itrial = 3
jtrial = 2
[[ 1. -1. -1.  1.]
 [ 1.  1.  1. -1.]
 [-1.  1.  1. -1.]
 [ 1.  1. -1. -1.]]
itrial = 3
jtrial = 1
[[ 1. -1. -1.  1.]
 [ 1.  1.  1. -1.]
 [-1.  1.  1. -1.]
 [ 1. -1. -1. -1.]]
itrial = 3
jtrial = 0
[[ 1. -1. -1.  1.]
 [ 1.  1.  1. -1.]
 [-1.  1.  1. -1.]
 [-1. -1. -1. -1.]]
itrial = 2
jtrial = 2
[[ 1. -1. -1.  1.]
 [ 1.  1.  1. -1.]
 [-1.  1. -1. -1.]
 [-1. -1. -1. -1.]]
itrial = 3
jtrial = 1
[[ 1. -1. -1.  1.]
 [ 1.  1.  1. -1.]
 [-1.  1. -1. -1.]
 [-1.  1. -1. -1.]]
itrial = 0
jtrial = 3
[[ 1. -1. -1. -1.]
 [ 1.  1.  1. -1.]
 [-1.  1. -1. -1.]
 [-1.  1. -1. -1.]]
itrial = 0
jtrial = 3
[[ 1. -1. -1.  1.]
 [ 1.  1.  1. -1.]
 [-1.  1. -1. -1.]
 [-1.  1. -1. -1.]]
itrial = 3