In [28]:
import numpy as np
import random

lx = 3
ly = lx

spin=np.zeros((lx,ly),dtype=float)

#initialise spins randomly

for i in range(lx):
    for j in range(ly):
        r=random.random()
        if(r<0.5): spin[i,j]=-1
        if(r>=0.5): spin[i,j]=1

print(spin)

def E_spin(spin, lx , ly):
    '''spin: numpy array
             spin matrix

       lx, ly: Interger
               Dimensions of the spin array 
    '''
    spin_x = spin
    print(f"{spin = }")
   
    E = 0
    for i in range(lx):
        for j in range(ly):
            E += -spin_x[i, j]*(spin_x[np.mod(i-1,lx),j] + spin_x[np.mod(i+1, lx),j] + spin_x[i,np.mod(j-1,ly)] + spin_x[i,np.mod(j+1,ly)])
            spin_x[i, j] = 0
    print(f"{spin = }")
    # why does the spin array become all zeros, spin_X sould be all zeros but the but spin should not
    return E

# I calculate the energy of a point and then once I calculated all the the interactions with nearest neighbours I set the spin to zero

[[-1.  1.  1.]
 [-1. -1.  1.]
 [ 1. -1.  1.]]


## Find the energy of the array above

In [29]:
E = E_spin(spin, lx, ly)
print(f"{E = }")
print(spin)

spin = array([[-1.,  1.,  1.],
       [-1., -1.,  1.],
       [ 1., -1.,  1.]])
spin = array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
E = 2.0
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
a = np.array([[1,2],[3,4]])
print(a)
a[1,1] = 0
print(a)

[[1 2]
 [3 4]]
[[1 2]
 [3 0]]
